### ISSUE TITLE
Pandoc not finding chinese font

### ISSUE THREAD

**Issue by TheFern2** [TheFern2/vscode-gutenberg#1]
@sylviachency please do not open issues in the wrong repositories, the python script is completely different source code.

Your issue of not displaying chinese letters can be solved by following these steps https://chatgpt.com/share/8ae19ed0-5990-4d52-ad1e-a01117747da8

For specifying the font you can do it within the first page front matter or within  gutenberg.pandocCommandExtra of gutenberg settings and remember to restart vscode, close it and open it for settings to take place.

Source: https://tex.stackexchange.com/a/234796
```yaml
---
mainfont: Font-Regular.otf
mainfontoptions:
- BoldFont=Font-Bold.otf
- ItalicFont=Font-Italic.otf
- BoldItalicFont=Font-BoldItalic.otf
---
```

Add argument to pandocCommandExtra:
```
-V 'mainfont:Font-Regular.otf'
```
